### ISSUE TITLE
Website link?

### ISSUE THREAD

**Issue by bayaderpack** [art3xias23/go-blog#1]

**Comment by art3xias23** [comment]
Hey thanks for checking this out.

I think making the site live will be the next step.

I will be looking for a free solution where I can host the web app and the mongodb instance.

Will reply to your comment once its done.

**Comment by bayaderpack** [comment]
Try with amazon https://aws.amazon.com/cloudfront/pricing/?nc=sn&loc=3
https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

**Comment by art3xias23** [comment]
Hey,

 so I opted for using the Free Tier of the [MongoDb ](https://www.mongodb.com/pricing) Atlas could DBaas. The app is using the cloud db already.

And I will be using [always data](https://help.alwaysdata.com/en/) to host the go application.

**Comment by bayaderpack** [comment]
Good luck. If you need any help feel free to ping me :)

**Comment by art3xias23** [comment]
I could not make _always data_ work so I decided I would get a cheap cloud server from [Hetzner](https://www.hetzner.com/)
and I got a cheap domain from [Porkbun](https://porkbun.com/) who also provide you with the ssl certificates.

The site is hosted here. [https://blog.pragmatino.xyz/](https://blog.pragmatino.xyz/)

The mongodb posts are not showing up, so i will be adding logging and resolving that.

Edit 09/06/2024
Posts section is now accessible. Had to whitelist the hetzner server in Mongo Db Atlas.
